const USER_CREATE_SUCCESS = '用户创建成功'
const USER_LOGIN_SUCCESS = '用户登录成功'
const USER_LOGOUT_SUCCESS = '用户已退出登录'
const USER_BG_UPDATE_SUCCESS = '用户空间背景更新成功'
const USER_AVATAR_UPDATE_SUCCESS = '用户头像更新成功'
const USER_GET_SUCCESS_BY_SEARCH = '用户查询成功'
const USER_INFO_UPDATE_SUCCESS = '用户信息修改成功'
const PLAYER_GET_SUCCESS = '球员信息获取成功'
const INVITATION_GET_ONE_SUCCESS = '单个帖子信息获取成功'
const INVITATION_GET_SUCCESS = '帖子信息获取成功'
const INVITATION_CREATE_SUCCESS = '帖子创建成功'
const INVITATION_GET_BY_TAG_SUCCESS = '成功按帖子分类获取全部帖子信息'
const INVITATION_GET_BY_USERID_SUCCESS = '成功按用户id获取其发布的所有帖子'
const INVITATION_STARRED_SUCCESS = '成功点赞帖子'
const INVITATION_ORDER_BY_STARS = '成功获取按点赞排行的帖子'
const INVITATION_UNSTAR_SUCCESS = '成功取消点赞'
const INVITATION_IS_STARRED = '用户点赞过该帖子'
const INVITATION_STARRED_LIST_GET_SUCCESS = '成功获取用户点赞过的所有帖子'
const INVITATION_GET_BY_VAL_SUCCESS = '成功按帖子关键字获取相关帖子信息'
const INVITATION_UPDATE_SUCCESS = '成功更新帖子信息'
const INVITATION_GET_BY_OFFSET = '成功按照分页获取帖子信息'
const TAG_GET_SUCCESS = '成功获取所有标签'
const COMMENT_GET_SUCCESS = '评论列表获取成功'
const COMMENT_CREATE_SUCCESS = '评论创建成功'
const FRIEND_LIST_GET_SUCCESS = '好友列表获取成功'
const FRIEND_REQ_EXISTS = '已发送过请求, 请勿重新申请'
const FRIEND_REQ_SEND_SUCCESS = '已发送好友请求'
const FRIEND_REQ_SEND_ERROR = '好友请求发送失败'
const FRIEND_REQ_LIST_GET_SUCCESS = '好友请求列表获取成功'
const FRIEND_ADD_SUCCESS = '成功添加好友'
const FRIEND_DENY_SUCCESS = '已拒绝该好友的请求'
const CAROUSEL_GET_SUCCESS = '成功获取轮播图'
const MESSAGE_WITH_FRIEND_GET_SUCCESS = '与好友的聊天记录获取成功'
const MESSAGE_WITH_FRIEND_UNREAD_GET_SUCCESS = '与好友的未读信息获取成功'
const MESSAGE_READ_STATUS_UPDATE_SUCCESS = '已更新信息的阅读状态为已读'
const MESSAGE_SEND_SUCCESS = '消息发送成功'
const MESSAGE_ALL_UNREAD_GET_SUCCESS = '用户全部未读信息获取成功'
const BRAND_ALL_GET_SUCCESS = '成功获取所有品牌信息'

module.exports = {
    USER_CREATE_SUCCESS,
    USER_LOGIN_SUCCESS,
    USER_BG_UPDATE_SUCCESS,
    USER_LOGOUT_SUCCESS,
    USER_AVATAR_UPDATE_SUCCESS,
    USER_INFO_UPDATE_SUCCESS,
    USER_GET_SUCCESS_BY_SEARCH,
    PLAYER_GET_SUCCESS,
    INVITATION_GET_SUCCESS,
    INVITATION_CREATE_SUCCESS,
    INVITATION_GET_ONE_SUCCESS,
    INVITATION_GET_BY_TAG_SUCCESS,
    INVITATION_GET_BY_USERID_SUCCESS,
    INVITATION_STARRED_SUCCESS,
    INVITATION_ORDER_BY_STARS,
    INVITATION_UNSTAR_SUCCESS,
    INVITATION_STARRED_LIST_GET_SUCCESS,
    INVITATION_GET_BY_VAL_SUCCESS,
    INVITATION_IS_STARRED,
    INVITATION_UPDATE_SUCCESS,
    INVITATION_GET_BY_OFFSET,
    TAG_GET_SUCCESS,
    COMMENT_GET_SUCCESS,
    COMMENT_CREATE_SUCCESS,
    FRIEND_LIST_GET_SUCCESS,
    FRIEND_ADD_SUCCESS,
    FRIEND_REQ_EXISTS,
    FRIEND_REQ_SEND_SUCCESS,
    FRIEND_REQ_SEND_ERROR,
    FRIEND_REQ_LIST_GET_SUCCESS,
    FRIEND_DENY_SUCCESS,
    CAROUSEL_GET_SUCCESS,
    MESSAGE_WITH_FRIEND_GET_SUCCESS,
    MESSAGE_READ_STATUS_UPDATE_SUCCESS,
    MESSAGE_SEND_SUCCESS,
    MESSAGE_WITH_FRIEND_UNREAD_GET_SUCCESS,
    MESSAGE_ALL_UNREAD_GET_SUCCESS,
    BRAND_ALL_GET_SUCCESS
}